version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
            - run: yarn build
      - persist_to_workspace:
          paths: build
  docs-deploy:
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - attach_workspace:
          at: build
      - run:
        name: Disable jekyll builds
        command: touch build/.nojekyll
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "eslider@gmail.com"
            git config user.name "ci-build"
      - add_ssh_keys:
          fingerprints:
            - "93:93:2f:f8:61:03:56:da:50:cb:ab:ef:42:c8:2c:e6"
      - run:
          name: Deploy docs to gh-pages branch
          command: 'gh-pages --dotfiles --message "[skip ci] Updates" --dist build'
workflows:
  build:
    jobs:
      - build
      - docs-deploy:
        requires:
          - build
